-- manager-transaction · MySQL 物理表
DROP TABLE IF EXISTS users;
CREATE TABLE users (_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), created_by VARCHAR(255), __present VARCHAR(255));
DROP TABLE IF EXISTS products;
CREATE TABLE products (_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), category VARCHAR(255), price DOUBLE, created_by VARCHAR(255), __present VARCHAR(255));
DROP TABLE IF EXISTS inventories;
CREATE TABLE inventories (_id VARCHAR(64) PRIMARY KEY, product_id VARCHAR(255), warehouse VARCHAR(255), stock INT, warn_line INT, created_by VARCHAR(255), __present VARCHAR(255));
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (_id VARCHAR(64) PRIMARY KEY, order_no VARCHAR(255), buyer_id VARCHAR(255), status VARCHAR(255), created_by VARCHAR(255), __present VARCHAR(255));
DROP TABLE IF EXISTS order_items;
CREATE TABLE order_items (_id VARCHAR(64) PRIMARY KEY, order_id VARCHAR(255), product_id VARCHAR(255), quantity INT, unit_price DOUBLE, created_by VARCHAR(255), __present VARCHAR(255));
DROP TABLE IF EXISTS auto_orders;
CREATE TABLE auto_orders (_id INT AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(255), amount DOUBLE, __present VARCHAR(255));
DROP TABLE IF EXISTS users_deleted;
CREATE TABLE users_deleted (_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), created_by VARCHAR(255), __present VARCHAR(255), deleted_at BIGINT);
DROP TABLE IF EXISTS products_deleted;
CREATE TABLE products_deleted (_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), category VARCHAR(255), price DOUBLE, created_by VARCHAR(255), __present VARCHAR(255), deleted_at BIGINT);
DROP TABLE IF EXISTS inventories_deleted;
CREATE TABLE inventories_deleted (_id VARCHAR(64) PRIMARY KEY, product_id VARCHAR(255), warehouse VARCHAR(255), stock INT, warn_line INT, created_by VARCHAR(255), __present VARCHAR(255), deleted_at BIGINT);
DROP TABLE IF EXISTS orders_deleted;
CREATE TABLE orders_deleted (_id VARCHAR(64) PRIMARY KEY, order_no VARCHAR(255), buyer_id VARCHAR(255), status VARCHAR(255), created_by VARCHAR(255), __present VARCHAR(255), deleted_at BIGINT);
DROP TABLE IF EXISTS order_items_deleted;
CREATE TABLE order_items_deleted (_id VARCHAR(64) PRIMARY KEY, order_id VARCHAR(255), product_id VARCHAR(255), quantity INT, unit_price DOUBLE, created_by VARCHAR(255), __present VARCHAR(255), deleted_at BIGINT);
DROP TABLE IF EXISTS auto_orders_deleted;
CREATE TABLE auto_orders_deleted (_id INT, order_no VARCHAR(255), amount DOUBLE, __present VARCHAR(255), deleted_at BIGINT);
